spring:
  config:
    import: "classpath:quiz/questions.yaml"
  main:
    log-startup-info: false
    banner-mode: console
  output:
    ansi:
      enabled: ALWAYS

spring-quiz:
  title: "Тест по Spring Framework"
  report:
    enabled: true
    mode: "verbose"
    output:
      mode: "console"
      path: "./quiz-result.txt"
logging:
  level:
    ru.yandex.practicum.quiz: INFO
    root: WARN